name: actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REPO: docker.io/faumaray/crossbuild
jobs:
  crossbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t ${{ env.DOCKER_REPO }} .
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ env.DOCKER_REPO }}
